Zephia\MercadoLibre\Entity\CategoryPrediction:
  exclusion_policy: NONE
  properties:
    path_from_root:
      type: "array<Zephia\\MercadoLibre\\Entity\\CategoryPrediction>"
    prediction_probability:
      type: "float"
    shipping_modes:
      type: "array"
